apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: default
spec:
  replicas: 5
  strategy:
    blueGreen:
      activeService: nginx-active-svc
      inactiveService: nginx-inactive-svc
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: stable  # 라벨 일치 여부 확인
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
