apiVersion: v1
kind: Service
metadata:
  name: nginx-canary-svc
  namespace: default
spec:
  selector:
    app: nginx  # Rollout와 동일한 selector 사용
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
