apiVersion: v1
kind: Service
metadata:
  name: nginx-active-svc
  labels:
    version: stable  # Rollout 리소스에서 사용하는 version 라벨
spec:
  selector:
    app: nginx
    version: stable
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-preview-svc
  namespace: default
spec:
  selector:
    app: nginx
    version: canary  # Green 버전 (새로운 버전)
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

