apiVersion: v1
kind: Service
metadata:
  name: nginx-active-svc
  namespace: default
spec:
  selector:
    app: nginx
    version: stable  # Blue 버전 (기존 버전)
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-preview-svc
  namespace: default
spec:
  selector:
    app: nginx
    version: canary  # Green 버전 (새로운 버전)
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

